version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 5001 --reload
    ports:
      - "5001:5001"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - N8N_WEBHOOK_URL_TEST=http://n8n:5678/webhook-test/returning-user
      - N8N_WEBHOOK_URL_PRODUCTION=http://n8n:5678/webhook/returning-user
      - N8N_WEBHOOK_MODE=${N8N_WEBHOOK_MODE}
      - PORT=${PORT}
      - HOST=${HOST}
    depends_on:
      n8n:
        condition: service_healthy
    networks:
      - chatbot-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/health"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build: 
      context: ./frontend/chatbot-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_PROTOCOL=http
      - REACT_APP_WS_PROTOCOL=ws
      - REACT_APP_BACKEND_HOST=backend
      - REACT_APP_BACKEND_PORT=5001
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - chatbot-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 15s

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/workflows:ro
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_WEBHOOK_URL=http://n8n:5678
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_WORKFLOWS_FOLDER=/workflows
      - WEBHOOK_TUNNEL_URL=http://n8n:5678
      - NODE_ENV=production
      - N8N_METRICS=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PUBLIC_API_DISABLED=true
      - N8N_HIRING_BANNER_ENABLED=false
      - GENERIC_TIMEZONE=UTC
    networks:
      - chatbot-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  chatbot-network:
    driver: bridge

volumes:
  n8n_data:
    driver: local 